.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 110, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 117, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 85, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_text2int6 (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 96, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 47, in text2int
    raise ValueError("Invalid word: " + word)
ValueError: Invalid word: ninth

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.FF..F
======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 105, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 109, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 121, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
