FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_1.LongestWordTestAddWord.test_add_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_1.LongestWordTestAddWord.test_add_word_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_1.LongestWordTestAddWord.test_add_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_1.LongestWordTestAddWord.test_add_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_1.LongestWordTestAddWord.test_add_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_2.LongestWordTestAddWord.test_add_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_2.LongestWordTestAddWord.test_add_word_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_2.LongestWordTestAddWord.test_add_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_2.LongestWordTestAddWord.test_add_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_2.LongestWordTestAddWord.test_add_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_4.LongestWordTestAddWord.test_add_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_4.LongestWordTestAddWord.test_add_word_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_4.LongestWordTestAddWord.test_add_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_4.LongestWordTestAddWord.test_add_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_4.LongestWordTestAddWord.test_add_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
F
======================================================================
FAIL: test_construct_stop_word_list (ClassEval_62_0.NLPDataProcessorTestConstruct.test_construct_stop_word_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 39, in test_construct_stop_word_list
    self.assertEqual(stop_word_list, expected_stop_words)
AssertionError: None != ['a', 'an', 'the']

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_remove_stop_words (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 50, in test_remove_stop_words
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test'], ['This', 'is', 'apple'], ['This', 'is', 'dog']]

======================================================================
FAIL: test_remove_stop_words_2 (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 56, in test_remove_stop_words_2
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_remove_stop_words_3 (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 62, in test_remove_stop_words_3
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_remove_stop_words_4 (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 69, in test_remove_stop_words_4
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'a', 'test'], ['This', 'i[44 chars]og']]

======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 76, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_process (ClassEval_62_0.NLPDataProcessorTestProcess.test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 86, in test_process
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test.'], ['This', 'is', 'apple.'], ['This', 'is', 'dog.']]

======================================================================
FAIL: test_process_with_empty_string_list (ClassEval_62_0.NLPDataProcessorTestProcess.test_process_with_empty_string_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 91, in test_process_with_empty_string_list
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_process_with_single_word_sentences (ClassEval_62_0.NLPDataProcessorTestProcess.test_process_with_single_word_sentences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 97, in test_process_with_single_word_sentences
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['Hello', 'aa'], ['World']]

======================================================================
FAIL: test_process_with_stop_words_only (ClassEval_62_0.NLPDataProcessorTestProcess.test_process_with_stop_words_only)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 102, in test_process_with_stop_words_only
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_process_with_stop_words_only_2 (ClassEval_62_0.NLPDataProcessorTestProcess.test_process_with_stop_words_only_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 107, in test_process_with_stop_words_only_2
    self.assertEqual(words_list,[[], [], [], ['This']])
AssertionError: None != [[], [], [], ['This']]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F
======================================================================
FAIL: test_construct_stop_word_list (ClassEval_62_3.NLPDataProcessorTestConstruct.test_construct_stop_word_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 39, in test_construct_stop_word_list
    self.assertEqual(stop_word_list, expected_stop_words)
AssertionError: None != ['a', 'an', 'the']

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_remove_stop_words (ClassEval_62_3.NLPDataProcessorTestRemove.test_remove_stop_words)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 50, in test_remove_stop_words
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test'], ['This', 'is', 'apple'], ['This', 'is', 'dog']]

======================================================================
FAIL: test_remove_stop_words_2 (ClassEval_62_3.NLPDataProcessorTestRemove.test_remove_stop_words_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 56, in test_remove_stop_words_2
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_remove_stop_words_3 (ClassEval_62_3.NLPDataProcessorTestRemove.test_remove_stop_words_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 62, in test_remove_stop_words_3
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_remove_stop_words_4 (ClassEval_62_3.NLPDataProcessorTestRemove.test_remove_stop_words_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 69, in test_remove_stop_words_4
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'a', 'test'], ['This', 'i[44 chars]og']]

======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_3.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 76, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_process (ClassEval_62_3.NLPDataProcessorTestProcess.test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 86, in test_process
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test.'], ['This', 'is', 'apple.'], ['This', 'is', 'dog.']]

======================================================================
FAIL: test_process_with_empty_string_list (ClassEval_62_3.NLPDataProcessorTestProcess.test_process_with_empty_string_list)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 91, in test_process_with_empty_string_list
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_process_with_single_word_sentences (ClassEval_62_3.NLPDataProcessorTestProcess.test_process_with_single_word_sentences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 97, in test_process_with_single_word_sentences
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['Hello', 'aa'], ['World']]

======================================================================
FAIL: test_process_with_stop_words_only (ClassEval_62_3.NLPDataProcessorTestProcess.test_process_with_stop_words_only)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 102, in test_process_with_stop_words_only
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_process_with_stop_words_only_2 (ClassEval_62_3.NLPDataProcessorTestProcess.test_process_with_stop_words_only_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 107, in test_process_with_stop_words_only_2
    self.assertEqual(words_list,[[], [], [], ['This']])
AssertionError: None != [[], [], [], ['This']]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_1.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_1.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_1.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_1.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_1.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_1.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a
+ 


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_1.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student
+ 


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_1.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_1.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_1.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_2.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_2.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_2.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_2.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_2.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a
+ 


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student
+ 


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a
+ 


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student
+ 


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_add_word_1 (ClassEval_53_4.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 50, in test_add_word_1
    self.assertEqual(['hello'], longestWord.word_list)
AssertionError: Lists differ: ['hello'] != []

First list contains 1 additional elements.
First extra element 0:
'hello'

- ['hello']
+ []

======================================================================
FAIL: test_add_word_2 (ClassEval_53_4.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 56, in test_add_word_2
    self.assertEqual(['hello', 'world'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world'] != []

First list contains 2 additional elements.
First extra element 0:
'hello'

- ['hello', 'world']
+ []

======================================================================
FAIL: test_add_word_3 (ClassEval_53_4.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 63, in test_add_word_3
    self.assertEqual(['hello', 'world', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!'] != []

First list contains 3 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!']
+ []

======================================================================
FAIL: test_add_word_4 (ClassEval_53_4.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 71, in test_add_word_4
    self.assertEqual(['hello', 'world', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!'] != []

First list contains 4 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!']
+ []

======================================================================
FAIL: test_add_word_5 (ClassEval_53_4.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 80, in test_add_word_5
    self.assertEqual(['hello', 'world', '!', '!', '!'], longestWord.word_list)
AssertionError: Lists differ: ['hello', 'world', '!', '!', '!'] != []

First list contains 5 additional elements.
First extra element 0:
'hello'

- ['hello', 'world', '!', '!', '!']
+ []

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_find_longest_word_1 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 88, in test_find_longest_word_1
    self.assertEqual('a', longestWord.find_longest_word(sentence))
AssertionError: 'a' != ''
- a
+ 


======================================================================
FAIL: test_find_longest_word_3 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 99, in test_find_longest_word_3
    self.assertEqual('student', longestWord.find_longest_word(sentence))
AssertionError: 'student' != ''
- student
+ 


======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 105, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 112, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
F
======================================================================
FAIL: test_construct_stop_word_list (ClassEval_62_0.NLPDataProcessorTestConstruct)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 39, in test_construct_stop_word_list
    self.assertEqual(stop_word_list, expected_stop_words)
AssertionError: None != ['a', 'an', 'the']

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_remove_stop_words (ClassEval_62_0.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 50, in test_remove_stop_words
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test'], ['This', 'is', 'apple'], ['This', 'is', 'dog']]

======================================================================
FAIL: test_remove_stop_words_2 (ClassEval_62_0.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 56, in test_remove_stop_words_2
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_remove_stop_words_3 (ClassEval_62_0.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 62, in test_remove_stop_words_3
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_remove_stop_words_4 (ClassEval_62_0.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 69, in test_remove_stop_words_4
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'a', 'test'], ['This', 'i[44 chars]og']]

======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_0.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 76, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_process (ClassEval_62_0.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 86, in test_process
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test.'], ['This', 'is', 'apple.'], ['This', 'is', 'dog.']]

======================================================================
FAIL: test_process_with_empty_string_list (ClassEval_62_0.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 91, in test_process_with_empty_string_list
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_process_with_single_word_sentences (ClassEval_62_0.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 97, in test_process_with_single_word_sentences
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['Hello', 'aa'], ['World']]

======================================================================
FAIL: test_process_with_stop_words_only (ClassEval_62_0.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 102, in test_process_with_stop_words_only
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_process_with_stop_words_only_2 (ClassEval_62_0.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 107, in test_process_with_stop_words_only_2
    self.assertEqual(words_list,[[], [], [], ['This']])
AssertionError: None != [[], [], [], ['This']]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_construct_stop_word_list (ClassEval_62_3.NLPDataProcessorTestConstruct)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 39, in test_construct_stop_word_list
    self.assertEqual(stop_word_list, expected_stop_words)
AssertionError: None != ['a', 'an', 'the']

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_remove_stop_words (ClassEval_62_3.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 50, in test_remove_stop_words
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test'], ['This', 'is', 'apple'], ['This', 'is', 'dog']]

======================================================================
FAIL: test_remove_stop_words_2 (ClassEval_62_3.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 56, in test_remove_stop_words_2
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_remove_stop_words_3 (ClassEval_62_3.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 62, in test_remove_stop_words_3
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_remove_stop_words_4 (ClassEval_62_3.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 69, in test_remove_stop_words_4
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'a', 'test'], ['This', 'i[44 chars]og']]

======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_3.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 76, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_process (ClassEval_62_3.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 86, in test_process
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['This', 'is', 'test.'], ['This', 'is', 'apple.'], ['This', 'is', 'dog.']]

======================================================================
FAIL: test_process_with_empty_string_list (ClassEval_62_3.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 91, in test_process_with_empty_string_list
    self.assertEqual(words_list, [])
AssertionError: None != []

======================================================================
FAIL: test_process_with_single_word_sentences (ClassEval_62_3.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 97, in test_process_with_single_word_sentences
    self.assertEqual(words_list, expected_words_list)
AssertionError: None != [['Hello', 'aa'], ['World']]

======================================================================
FAIL: test_process_with_stop_words_only (ClassEval_62_3.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 102, in test_process_with_stop_words_only
    self.assertEqual(words_list, [[], [], []])
AssertionError: None != [[], [], []]

======================================================================
FAIL: test_process_with_stop_words_only_2 (ClassEval_62_3.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 107, in test_process_with_stop_words_only_2
    self.assertEqual(words_list,[[], [], [], ['This']])
AssertionError: None != [[], [], [], ['This']]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
